# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require 'xcodeproj'
unless Xcodeproj::Constants::COMPATIBILITY_VERSION_BY_OBJECT_VERSION.key?(70)
  compatibility_versions = Xcodeproj::Constants::COMPATIBILITY_VERSION_BY_OBJECT_VERSION
  Xcodeproj::Constants.send(:remove_const, :COMPATIBILITY_VERSION_BY_OBJECT_VERSION)
  Xcodeproj::Constants.const_set(
    :COMPATIBILITY_VERSION_BY_OBJECT_VERSION,
    compatibility_versions.merge(70 => 'Xcode 16.0'),
  )
end
 
source 'https://cdn.cocoapods.org/'
source 'https://github.com/SumSubstance/Specs.git'
 
platform :ios, '15.1'
prepare_react_native_project!
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
 
target 'valens' do
  config = use_native_modules!
 
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
 
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
 
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
   
    # Fix Swift compilation and deployment target issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set minimum deployment target to match platform
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
       
        # Fix Swift version
        config.build_settings['SWIFT_VERSION'] = '5.0'
       
        # Disable bitcode
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        # Some React Native pods include non-modular headers when built as frameworks.
        # This avoids build failures like: non-modular-include-in-framework-module.
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/../../node_modules/react-native/ReactCommon"'
       
        # Fix expo-localization Swift issue
        if target.name == 'ExpoLocalization'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        end

        # Xcode 26's Apple clang trips over fmt's C++20 consteval path.
        # Building fmt as C++17 avoids the consteval compile errors while
        # leaving the rest of React Native on its generated settings.
        if target.name == 'fmt'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end
 
 
