/**
 * Writes `src/shims/env.js` from the project root `.env` so Metro can resolve
 * env values without `import from '@env'` (which Metro resolves before Babel).
 * Called from metro.config.js on each Metro start.
 */
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const SHIM_PATH = path.join(ROOT, 'src', 'shims', 'env.js');

function writeEnvShim() {
  let env = {};
  try {
    if (fs.existsSync(ENV_PATH)) {
      env = dotenv.parse(fs.readFileSync(ENV_PATH));
    }
  } catch (e) {
    console.warn('[writeEnvShim] Could not read .env:', e.message);
  }

  const out = `/* eslint-disable */
/* AUTO-GENERATED by scripts/writeEnvShim.js — do not edit */
export const BASE_URL = ${JSON.stringify(env.BASE_URL ?? '')};
export const API_PARAM = ${JSON.stringify(env.API_PARAM ?? '')};
export const YOUTUBE_DATA_API_KEY = ${JSON.stringify(
    env.YOUTUBE_DATA_API_KEY ?? '',
  )};
`;

  fs.mkdirSync(path.dirname(SHIM_PATH), {recursive: true});
  fs.writeFileSync(SHIM_PATH, out, 'utf8');
}

module.exports = {writeEnvShim};

if (require.main === module) {
  writeEnvShim();
}
