import { StyleSheet } from "react-native";

export default StyleSheet.create({
    wrapper: {
        flex: 1,
    },
    container: {
        flex: 1,
        paddingBottom: 50,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    backButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    backIcon: {
        fontSize: 28,
        color: '#5B21B6',
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1F2937',
    },
    placeholder: {
        width: 40,
    },
    mainHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    menuIcon: {
        fontSize: 24,
        color: '#5B21B6',
    },
    mainTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1F2937',
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    profileCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
    },
    avatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#5B21B6',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 15,
    },
    avatarText: {
        fontSize: 24,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    profileName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 4,
    },
    profileUsername: {
        fontSize: 14,
        color: '#6B7280',
    },
    section: {
        marginBottom: 20,
    },
    categoryTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#5B21B6',
        marginBottom: 12,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        overflow: 'hidden',
    },
    settingItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    settingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    settingIcon: {
        fontSize: 20,
        marginRight: 12,
    },
    settingTitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#1F2937',
    },
    settingRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    settingValue: {
        fontSize: 14,
        color: '#6B7280',
        marginRight: 8,
    },
    arrow: {
        fontSize: 24,
        color: '#9CA3AF',
    },
    avatarContainer: {
        alignItems: 'center',
        paddingVertical: 20,
    },
    changePhotoButton: {
        marginTop: 12,
        paddingVertical: 8,
        paddingHorizontal: 16,
        backgroundColor: '#5B21B6',
        borderRadius: 8,
    },
    changePhotoText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#5B21B6',
        marginBottom: 12,
        textTransform: 'uppercase',
    },
    inputGroup: {
        marginBottom: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
    },
    inputLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
        marginBottom: 8,
    },
    input: {
        fontSize: 16,
        color: '#1F2937',
        paddingVertical: 4,
    },
    saveButton: {
        backgroundColor: '#5B21B6',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginBottom: 20,
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    verificationCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 30,
        alignItems: 'center',
        marginBottom: 20,
    },
    verificationBadge: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#10B981',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    verificationIcon: {
        fontSize: 40,
        color: '#FFFFFF',
    },
    verificationTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 8,
    },
    verificationSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
    },
    verificationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    verificationItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    verificationItemIcon: {
        fontSize: 24,
        marginRight: 12,
    },
    verificationItemTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    verificationItemSubtitle: {
        fontSize: 12,
        color: '#6B7280',
    },
    verifiedBadge: {
        backgroundColor: '#D1FAE5',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    verifiedText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#10B981',
    },
    unVerifiedBadge: {
        backgroundColor: '#fce4e4ff',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    unVerifiedText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#c82929ff',
    },
    radioGroup: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        overflow: 'hidden',
    },
    radioItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    radio: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#5B21B6',
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    radioSelected: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#5B21B6',
    },
    radioTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    radioSubtitle: {
        fontSize: 12,
        color: '#6B7280',
    },
    toggleItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    toggleTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    toggleSubtitle: {
        fontSize: 12,
        color: '#6B7280',
    },
    dangerButton: {
        backgroundColor: '#FEE2E2',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
    },
    dangerButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#DC2626',
    },
    infoCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 30,
        alignItems: 'center',
        marginBottom: 20,
    },
    infoIcon: {
        fontSize: 60,
        marginBottom: 16,
    },
    infoTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 8,
    },
    infoDescription: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
    },
    methodItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    methodLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    methodIcon: {
        fontSize: 24,
        marginRight: 12,
    },
    methodTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    methodSubtitle: {
        fontSize: 12,
        color: '#6B7280',
    },
    loginItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    loginLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    loginStatusDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 12,
    },
    loginStatusCurrent: {
        backgroundColor: '#10B981',
    },
    loginStatusSuccess: {
        backgroundColor: '#6B7280',
    },
    loginStatusFailed: {
        backgroundColor: '#EF4444',
    },
    loginDevice: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    loginLocation: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 2,
    },
    loginTime: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    currentBadge: {
        backgroundColor: '#D1FAE5',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    currentText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#10B981',
    },
    failedBadge: {
        backgroundColor: '#FEE2E2',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    failedText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#DC2626',
    },
    logoutButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#5B21B6',
    },
    logoutButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#5B21B6',
    },
});