/* eslint-disable */
/* AUTO-GENERATED by scripts/writeEnvShim.js — do not edit */
export const BASE_URL = "";
export const API_PARAM = "";
export const YOUTUBE_DATA_API_KEY = "AIzaSyC5cTUZJzSyzfO6WHNZgNNKtws6Ey9tvik";
